### ISSUE TITLE
Error when running unimodal experiment

### ISSUE THREAD

**Issue by marcostx** [soujanyaporia/multimodal-fusion#4]
Hi,
When I run the command:

`python3 run.py --unimodal True --fusion True`

the output is

> Traceback (most recent call last):
>   File "run.py", line 384, in <module>
>     unimodal(mode, args.data, args.classes)
>   File "run.py", line 276, in unimodal
>     test_feed_dict)
>   File "/Users/marcostexeira/tensorflow3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
>     run_metadata_ptr)
>   File "/Users/marcostexeira/tensorflow3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1113, in _run
>     str(subfeed_t.get_shape())))
> 
> ValueError: Cannot feed value of shape (31, 63) for Tensor 'y:0', which has shape '(?, 63, 2)'

Is this related to running locally, rather than GPU?

**Comment by gangeshwark** [comment]
Hi,
Thanks for notifying. The issue has been fixed.
Please try again with the new code.
